branches:
  only:
  - master

env:
  global:
  - secure: "X4QgOIMZHMGHjF+P0I/F2MesSB3Zt8Hm+ra81oG9ockbSscqV1KQDu4B3KIEQLZ152dpIY3eWOtr318hBqgDpMp8pvsGDOzCrpJWxQvEhXCWskgSMUkaxiM9OSJl2a0zvI0+qx06bSuXe4Q6mxWifjG1TBojGy9MLRyXELfRilcmb3mgvQf1wfXVpgWlTB0uZZhVDDk8OSU2UMlibHk8Q5HdhEdQW2IftBb0L4gRrTuGdUpk2klrFxKn/3qbAJ62PguVZ58hSgB+Ua8LYyQ7dG8Cc8+aJGe1xI7CL239E4o47Ix4mF9d0kPzxK1sJMRZkPVU80FNitU8r+9PVw6w64w2OrBOn3EtyQ9XF/m2HpqjtmC0C12IeVeiIZrOCOU/02R/HfI6RJ7MhWDnDc6Mg9BxyXhJKsujngFZiECQNrVryIE5Iu6XUQncoBO+JL/P4eUbgTC9svN0DcpoYUYJGQAU8FZLWqEogGHO08vnAqz9tGruEw2h6jGAUJR0WZVP3AOEsOQEyZ2hOjtbsPvhGcX/cLDl2xCXSb1EpKerBQ0GaohBBoEQ0+igxxOx8ULiYBuWdGRngqDe0VKwZuXr38JoAM+7DIK+9+0QvPBnaOH/s9uCLMfsWWzOC6dBBSn44v1nug/soI78oubAf/qMUWFR6rBbGyTyYa2xYC7A/Xs="
  - secure: "dZVmWY/wdIh1ljOZSbE6ZbBbHtDDttzHM0iu/vpBJELiudED6ODx/r4TDckUzEV4jW63BiVDPgMioyWJn6UrF2msTDdu4qFotRj4KOgVIQK3zAPi/VgR7c+jSL95+V0OnhLZVmFrqlRY+DO3rgma0ROiPIWqfEosILn3C1KhKtY7V6nRvF0grXH5HuWzR+JwcZD41Jrk7WQHu/eIUDmbwjPRIvNSPxtrZSkPqB1mqO/NHdxvbld4Mlm5IL6pRnIaHSAMV5/dmDyEZ24OxgSWuKL23BHmDTF1nQG2djTNX7grNI263iykfcQHp1i19P/thnzvhoyVKpBjFK09O8zCGmTmBShMU26D7N8dWKgmArY4nF6ngqtKxmP8rbM2jT7iwH5csAQc5CZEVGMv/mUm/CHXQRt5Mjksii3/V7gdu9OPSRFklqRfXFvdoVLUtwjTNUBh6wJ3Qif5etk05VwdFuM+/Zx+CUOR5TPv+NdifHUQJygRMRoOIlf8mlqavqYLAA6GIxxhWERFS8KWlMo0IYun9pis8cfpGYA7/188dY2082JV1faaoyjfFNrFoYWjWiYLMhP+lBs1zfxL4KuABaqM7EWYxK6lOjxJ87i/S3hwUtBXFHtC5t4rh98ZtSuUl4ADYoGfSqK8FCoviVA+OqlbvaWBKEKmN5c0ksI2I+U="

script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t ryms/routes_front:latest .
- docker push ryms/routes_front:latest
